coverage:
  range: 60...80
  status:
    project: off
    patch: off

codecov:
  ci:
    - jenkins.symboxtra.dynu.net

flags:
  windows:
    paths:
      - src/
  osx:
    paths:
      - src/
  linux:
    paths:
      - src/

ignore:
    - "src/libs/"
    - "**/main.cpp"
    - "src/audio/OSXDriver"
    - "src/audio/OSXDaemon"
